server:
  port: 9099
  servlet:
    context-path: /gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: operate-service
          uri: http://localhost:9001
          predicates:
            - Path=/operate/**
